# Generated by Django 5.2.7 on 2025-11-03 22:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0042_remove_programa_regla_reinscripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('one_time', 'Pago único'), ('recurring', 'Recurrente')], default='one_time', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('interval', models.CharField(default='month', max_length=16)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invites', to='alumnos.alumno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one_time', 'Pago único'), ('subscription', 'Suscripción')], max_length=16)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado'), ('active', 'Activo'), ('incomplete', 'Incompleto'), ('past_due', 'Atrasado'), ('canceled_sub', 'Cancelada')], default='created', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('checkout_session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='alumnos.alumno')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cobros.billinginvite')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='alumnos.alumno')),
            ],
        ),
    ]
