# Generated by Django 5.2.7 on 2025-11-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
