# Generated by Django 5.2.7 on 2025-11-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0043_pagodiario_payment_record'),
        ('cobros', '0002_alter_paymentrecord_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='cargo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='alumnos.cargo'),
        ),
    ]
