# Generated by Django 5.2.7 on 2025-11-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0045_alter_informacionescolar_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ListadoMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listados', to='alumnos.programa')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('programa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ListadoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listados', to='alumnos.alumno')),
                ('listado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.listadomaterias')),
            ],
            options={
                'ordering': ['-agregado_en'],
                'unique_together': {('listado', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='ListadoMateriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('listado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academico.listadomaterias')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='academico.materia')),
            ],
            options={
                'ordering': ['fecha_inicio', 'materia__codigo'],
                'unique_together': {('listado', 'materia')},
            },
        ),
    ]
