# Generated by Django 5.2.7 on 2025-11-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('alumnos', '0045_alter_informacionescolar_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('capturado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_materia', to='alumnos.alumno')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.listadomateriaitem')),
            ],
            options={
                'ordering': ['item__fecha_inicio', 'alumno__numero_estudiante'],
                'indexes': [models.Index(fields=['item', 'alumno'], name='academico_c_item_id_506545_idx')],
                'unique_together': {('item', 'alumno')},
            },
        ),
    ]
