# Generated by Django 5.2.7 on 2025-11-11 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_calificacion'),
        ('alumnos', '0045_alter_informacionescolar_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['programa__codigo', 'codigo']},
        ),
        migrations.AddField(
            model_name='materia',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='alumnos.programa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('programa', 'codigo')},
        ),
    ]
