# Generated by Django 5.2.7 on 2025-11-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_materia_options_materia_programa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre(s)')),
                ('apellido_p', models.CharField(blank=True, max_length=120, verbose_name='Apellido paterno')),
                ('apellido_m', models.CharField(blank=True, max_length=120, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, verbose_name='Correo institucional')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario del sistema asociado (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellido_p', 'apellido_m', 'nombre'],
                'indexes': [models.Index(fields=['apellido_p', 'apellido_m', 'nombre'], name='academico_p_apellid_efe369_idx'), models.Index(fields=['activo'], name='academico_p_activo_c7e55c_idx')],
            },
        ),
    ]
