# Generated by Django 5.2.7 on 2025-11-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='academico.profesor'),
        ),
    ]
