# Generated by Django 5.2.7 on 2025-11-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_calificacion_fecha_calificacion_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Especialidad'),
        ),
    ]
