# Generated by Django 5.2.7 on 2025-11-15 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_profesor_ciudad_profesor_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False, verbose_name='Es titular')),
                ('activo', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_profesor', to='academico.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.profesor')),
            ],
            options={
                'verbose_name': 'Asignación de profesor a materia',
                'verbose_name_plural': 'Asignaciones de profesor a materia',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='materias', through='academico.ProfesorMateria', to='academico.profesor'),
        ),
        migrations.AddIndex(
            model_name='profesormateria',
            index=models.Index(fields=['materia'], name='academico_p_materia_7c2a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='profesormateria',
            index=models.Index(fields=['profesor'], name='academico_p_profeso_d047ab_idx'),
        ),
        migrations.AddIndex(
            model_name='profesormateria',
            index=models.Index(fields=['es_titular'], name='academico_p_es_titu_1fb1bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='profesormateria',
            constraint=models.UniqueConstraint(condition=models.Q(('es_titular', True)), fields=('materia',), name='uniq_titular_por_materia'),
        ),
        migrations.AlterUniqueTogether(
            name='profesormateria',
            unique_together={('profesor', 'materia')},
        ),
    ]
