# Generated by Django 5.2.7 on 2025-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_profesormateria_materia_profesores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='clave_interbancaria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clave interbancaria'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='lugar_de_trabajo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de trabajo'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo_De_deposito',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de depósito'),
        ),
    ]
