# Generated by Django 5.2.7 on 2025-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_profesor_banco_profesor_clave_interbancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grado_academico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Grado académico'),
        ),
    ]
