# Generated by Django 5.2.7 on 2025-10-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('numero_estudiante', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Número de estudiante')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('estatus_academico', models.CharField(blank=True, max_length=60, verbose_name='Estatus académico')),
                ('estatus_administrativo', models.CharField(blank=True, max_length=60, verbose_name='Estatus administrativo')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido_p', models.CharField(blank=True, max_length=120, verbose_name='Apellido paterno')),
                ('apellido_m', models.CharField(blank=True, max_length=120, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('programa', models.CharField(blank=True, max_length=120)),
                ('estatus', models.CharField(blank=True, max_length=60)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['apellido_p', 'apellido_m', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('recurrente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cargo', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=50)),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='alumnos.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.conceptopago')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(blank=True, max_length=40)),
                ('banco', models.CharField(blank=True, max_length=60)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='alumnos.alumno')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='alumnos.cargo')),
            ],
        ),
    ]
