# Generated by Django 5.2.7 on 2025-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['numero_estudiante'], name='alumnos_alu_numero__174d29_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['curp'], name='alumnos_alu_curp_dd4e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['apellido_p', 'apellido_m'], name='alumnos_alu_apellid_2bb7f5_idx'),
        ),
    ]
