# Generated by Django 5.2.7 on 2025-10-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='sede',
        ),
        migrations.AddField(
            model_name='informacionescolar',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='alumnos.sede'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
    ]
