# Generated by Django 5.2.7 on 2025-10-09 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_curp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Estado/Provincia',
                'verbose_name_plural': 'Estados/Provincias',
                'ordering': ['pais__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='alumnos.estado'),
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo_iso2', models.CharField(blank=True, max_length=2, verbose_name='Código ISO-2')),
                ('codigo_iso3', models.CharField(blank=True, max_length=3, verbose_name='Código ISO-3')),
                ('requiere_estado', models.BooleanField(default=False, help_text='Si es verdadero, el alumno debe seleccionar un estado/provincia.', verbose_name='¿Requiere estado/provincia?')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='alumnos_pai_nombre_bd0e2a_idx'), models.Index(fields=['codigo_iso2'], name='alumnos_pai_codigo__38fef7_idx'), models.Index(fields=['codigo_iso3'], name='alumnos_pai_codigo__998ed5_idx')],
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='alumnos.pais'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='alumnos.pais'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['pais'], name='alumnos_alu_pais_id_0a317d_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['estado'], name='alumnos_alu_estado__c40fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['pais', 'nombre'], name='alumnos_est_pais_id_a1834c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('pais', 'nombre')},
        ),
    ]
