# Generated by Django 5.2.7 on 2025-10-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_sede_informacionescolar_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programa', to='alumnos.programa'),
        ),
    ]
