# Generated by Django 5.2.7 on 2025-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_informacionescolar_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='fin_programa',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del programa'),
        ),
    ]
