# Generated by Django 5.2.7 on 2025-10-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_informacionescolar_fin_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el alumno se dio de alta en el sistema', null=True),
        ),
    ]
