# Generated by Django 5.2.7 on 2025-10-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_informacionescolar_fecha_alta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['numero_estudiante']},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_estudiante',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número de estudiante'),
        ),
    ]
