# Generated by Django 5.2.7 on 2025-10-10 15:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_fecha_nacimiento_alumno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre(s)'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Programas (código)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Cursos')),
                ('meses_programa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meses Programa')),
                ('colegiatura', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Colegiatura')),
                ('inscripcion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Inscripción')),
                ('reinscripcion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Reinscripción')),
                ('equivalencia', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Equivalencia')),
                ('titulacion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Titulación')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='alumnos_pro_codigo_8f6308_idx'), models.Index(fields=['nombre'], name='alumnos_pro_nombre_b06565_idx'), models.Index(fields=['activo'], name='alumnos_pro_activo_008014_idx')],
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='alumnos.programa', verbose_name='Programa'),
        ),
    ]
