# Generated by Django 5.2.7 on 2025-10-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_alumno_options_alter_alumno_numero_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['-numero_estudiante']},
        ),
        migrations.CreateModel(
            name='PagoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_alumno_raw', models.CharField(blank=True, max_length=40, verbose_name='No.Alumno (texto crudo)')),
                ('curp_raw', models.CharField(blank=True, max_length=20, verbose_name='CURP (crudo)')),
                ('nombre_raw', models.CharField(blank=True, max_length=200, verbose_name='Nombre (crudo)')),
                ('folio', models.CharField(blank=True, max_length=40, verbose_name='Folio')),
                ('sede_text', models.CharField(blank=True, max_length=120, verbose_name='SEDE (texto)')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto')),
                ('grado', models.CharField(blank=True, max_length=20, verbose_name='Grado')),
                ('forma_pago', models.CharField(blank=True, max_length=40, verbose_name='Forma de pago')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('concepto', models.CharField(blank=True, max_length=120, verbose_name='Concepto')),
                ('pago_detalle', models.CharField(blank=True, max_length=200, verbose_name='Pago (detalle)')),
                ('programa_text', models.CharField(blank=True, max_length=200, verbose_name='Programa (texto)')),
                ('no_autorizacion', models.CharField(blank=True, max_length=80, verbose_name='No. de auto')),
                ('emision', models.CharField(blank=True, max_length=40, verbose_name='Emisión')),
                ('archivo_origen', models.CharField(blank=True, max_length=260, verbose_name='Archivo origen')),
                ('hoja_origen', models.CharField(blank=True, max_length=120, verbose_name='Hoja origen')),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fila origen (1-based)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diario', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Pago (diario)',
                'verbose_name_plural': 'Pagos (diario)',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['folio'], name='alumnos_pag_folio_73fbe7_idx'), models.Index(fields=['fecha'], name='alumnos_pag_fecha_222c97_idx'), models.Index(fields=['emision'], name='alumnos_pag_emision_0ff4bc_idx'), models.Index(fields=['numero_alumno_raw'], name='alumnos_pag_numero__5917bf_idx'), models.Index(fields=['curp_raw'], name='alumnos_pag_curp_ra_f484d9_idx')],
            },
        ),
    ]
