# Generated by Django 5.2.7 on 2025-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_alumno_options_pagodiario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagodiario',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pagodiario',
            name='alumnos_pag_emision_0ff4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagodiario',
            name='alumnos_pag_numero__5917bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagodiario',
            name='alumnos_pag_curp_ra_f484d9_idx',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='archivo_origen',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='curp_raw',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='fila_origen',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='hoja_origen',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='no_autorizacion',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='nombre_raw',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='numero_alumno_raw',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='programa_text',
        ),
        migrations.RemoveField(
            model_name='pagodiario',
            name='sede_text',
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='curp',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='no_auto',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='numero_alumno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='programa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagodiario',
            name='sede',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='concepto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='emision',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='grado',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pagodiario',
            name='pago_detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='pagodiario',
            index=models.Index(fields=['curp'], name='alumnos_pag_curp_a859f0_idx'),
        ),
    ]
