# Generated by Django 5.2.7 on 2025-10-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alter_pagodiario_options_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(default='global', max_length=32, unique=True)),
                ('ultimo_numero', models.BigIntegerField(default=0)),
            ],
        ),
    ]
