# Generated by Django 5.2.7 on 2025-10-17 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_contadoralumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email_institucional',
            field=models.EmailField(blank=True, help_text='Usa siempre el correo @iuaf.edu.mx para Classroom/Zoom.', max_length=254, validators=[django.core.validators.RegexValidator(message='El correo institucional debe ser @iuaf.edu.mx', regex='^[^@\\s]+@iuaf\\.edu\\.mx$')], verbose_name='Correo electrónico institucional'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico personal'),
        ),
    ]
