# Generated by Django 5.2.7 on 2025-10-17 18:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_alumno_email_institucional_alter_alumno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamiento',
            name='monto_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo si el tipo es 'Monto fijo'. Ej.: 1500.00", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto fijo a descontar'),
        ),
        migrations.AddField(
            model_name='financiamiento',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo si el tipo es 'Porcentaje'. Ej.: 15.5 = 15.5%.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='financiamiento',
            name='tipo_descuento',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], default='ninguno', help_text='Selecciona si el descuento es porcentual o de monto fijo.', max_length=20, verbose_name='Tipo de descuento'),
        ),
    ]
