# Generated by Django 5.2.7 on 2025-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_financiamiento_monto_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionescolar',
            name='inicio_programa',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del programa'),
        ),
    ]
