# Generated by Django 5.2.7 on 2025-10-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_informacionescolar_inicio_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_academico',
            field=models.CharField(blank=True, choices=[('vigente', 'VIGENTE'), ('egresado', 'EGRESADO'), ('baja_tmp', 'BAJA TEMPORAL'), ('baja_def', 'BAJA DEFINITIVA'), ('titulacion', 'EN TITULACIÓN')], default='vigente', max_length=20, verbose_name='Estatus académico'),
        ),
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_administrativo',
            field=models.CharField(blank=True, choices=[('vigente', 'VIGENTE'), ('egresado', 'EGRESADO'), ('baja_tmp', 'BAJA TEMPORAL'), ('baja_def', 'BAJA DEFINITIVA')], default='vigente', max_length=20, verbose_name='Estatus administrativo'),
        ),
    ]
