# Generated by Django 5.2.7 on 2025-10-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_alter_informacionescolar_estatus_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_academico',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('EGRESADO', 'EGRESADO'), ('BAJA TEMPORAL', 'BAJA TEMPORAL'), ('BAJA DEFINITIVA', 'BAJA DEFINITIVA'), ('EN TITULACIÓN', 'EN TITULACIÓN')], default='vigente', max_length=20, verbose_name='Estatus académico'),
        ),
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_administrativo',
            field=models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('EGRESADO', 'EGRESADO'), ('BAJA TEMPORAL', 'BAJA TEMPORAL'), ('BAJA DEFINITIVA', 'BAJA DEFINITIVA')], default='vigente', max_length=20, verbose_name='Estatus administrativo'),
        ),
    ]
