# Generated by Django 5.2.7 on 2025-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_alter_informacionescolar_estatus_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionescolar',
            name='requiere_datos_de_facturacion',
            field=models.BooleanField(default=False, verbose_name='¿Requiere datos de facturación?'),
        ),
    ]
