# Generated by Django 5.2.7 on 2025-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_informacionescolar_requiere_datos_de_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ver_todos_los_pagos',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario verá todos los pagos (sin límite de años).'),
        ),
    ]
