# Generated by Django 5.2.7 on 2025-10-18 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_userprofile_ver_todos_los_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo (ej. 'Clip Prod', 'Clip Sandbox')", max_length=60)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.TextField(blank=True, help_text='Secret key (API secret). Guardar con precaución.', null=True)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False, help_text='Si está activa, será la usada por defecto en helpers.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial Clip',
                'verbose_name_plural': 'Credenciales Clip',
                'ordering': ('-updated_at',),
            },
        ),
    ]
