# Generated by Django 5.2.7 on 2025-10-18 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_clipcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Creada'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Fallida'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], db_index=True, default='created', max_length=12)),
                ('clip_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checkout_url', models.URLField(blank=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('last_webhook', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_clip', to='alumnos.alumno')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_clip', to='alumnos.cargo')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
