# Generated by Django 5.2.7 on 2025-10-18 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_clippaymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Etiqueta (ej. 'Twilio Prod' o 'Twilio Dev')", max_length=60)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox / Dev'), ('prod', 'Producción')], default='sandbox', max_length=20)),
                ('active', models.BooleanField(default=False, help_text='Usar esta configuración por defecto')),
                ('account_sid', models.CharField(max_length=64)),
                ('auth_token', models.TextField(help_text='Auth Token (se recomienda cifrar en BD)')),
                ('messaging_service_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('sms_from', models.CharField(blank=True, help_text='Ej. +1234567890', max_length=32, null=True)),
                ('whatsapp_from', models.CharField(blank=True, help_text='Ej. whatsapp:+14155238886 (sandbox) o tu número verificado', max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config de Twilio',
                'verbose_name_plural': 'Configs de Twilio',
                'ordering': ('-updated_at',),
            },
        ),
    ]
