# Generated by Django 5.2.7 on 2025-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_twilioconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twilioconfig',
            name='environment',
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='default_sms_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='default_wa_to',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='twilioconfig',
            name='env',
            field=models.CharField(choices=[('sandbox', 'sandbox'), ('prod', 'prod')], default='sandbox', max_length=16),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='account_sid',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='auth_token',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='messaging_service_sid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='sms_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='twilioconfig',
            name='whatsapp_from',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
