# Generated by Django 5.2.7 on 2025-10-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0022_alumno_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estatus académico',
                'verbose_name_plural': 'Estatus académicos',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estatus administrativo',
                'verbose_name_plural': 'Estatus administrativos',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='puede_editar_todo',
            field=models.BooleanField(default=False, verbose_name='Puede editar'),
        ),
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciones_academicas', to='alumnos.estatusacademico', verbose_name='Estatus académico'),
        ),
        migrations.AlterField(
            model_name='informacionescolar',
            name='estatus_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciones_administrativas', to='alumnos.estatusadministrativo', verbose_name='Estatus administrativo'),
        ),
    ]
