# Generated by Django 5.2.7 on 2025-10-21 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0023_estatusacademico_estatusadministrativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionescolar',
            name='precio_reinscripcion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio de reinscripción'),
        ),
    ]
