# Generated by Django 5.2.7 on 2025-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0024_informacionescolar_precio_reinscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('monto', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('signo', models.SmallIntegerField(blank=True, choices=[(-1, 'Cargo'), (1, 'Abono')], null=True)),
                ('sucursal', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('referencia_numerica', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('referencia_alfanumerica', models.TextField(blank=True, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('autorizacion', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('emisor_nombre', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('institucion_emisora', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('descripcion_raw', models.TextField(blank=True, null=True)),
                ('source_sheet_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('source_sheet_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('source_gid', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('uid_hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha', 'tipo'], name='alumnos_mov_fecha_5e3de7_idx'), models.Index(fields=['referencia_numerica', 'autorizacion'], name='alumnos_mov_referen_cc71a8_idx'), models.Index(fields=['emisor_nombre'], name='alumnos_mov_emisor__efde8f_idx'), models.Index(fields=['institucion_emisora'], name='alumnos_mov_institu_79d3ca_idx')],
            },
        ),
    ]
