# Generated by Django 5.2.7 on 2025-10-22 17:25

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0026_documentotipo_alter_movimientobanco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programadocumentorequisito',
            options={'ordering': ['programa__codigo', 'tipo__nombre'], 'verbose_name': 'Requisito documental de Programa', 'verbose_name_plural': 'Requisitos documentales de Programas'},
        ),
        migrations.AddField(
            model_name='programadocumentorequisito',
            name='aplica_a',
            field=models.CharField(choices=[('todos', 'Todos'), ('solo_extranjeros', 'Solo extranjeros'), ('solo_nacionales', 'Solo nacionales')], default='todos', help_text='Define si este documento lo deben subir todos, solo extranjeros, o solo nacionales.', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoalumno',
            name='archivo',
            field=models.FileField(upload_to=alumnos.models.doc_upload_path),
        ),
    ]
