# Generated by Django 5.2.7 on 2025-10-22 17:34

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0027_alter_programadocumentorequisito_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoalumno',
            name='archivo',
            field=models.FileField(upload_to=alumnos.models.doc_upload_path),
        ),
    ]
