# Generated by Django 5.2.7 on 2025-10-22 17:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0028_alter_documentoalumno_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamiento',
            name='beca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Beca'),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='monto_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto fijo a descontar'),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='tipo_descuento',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], default='ninguno', max_length=20, verbose_name='Tipo de descuento'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='requiere_estado',
            field=models.BooleanField(default=False, verbose_name='¿Requiere estado/provincia?'),
        ),
        migrations.DeleteModel(
            name='DocumentosAlumno',
        ),
    ]
