# Generated by Django 5.2.7 on 2025-10-23 17:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0029_alter_financiamiento_beca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='precio_colegiatura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio colegiatura'),
        ),
    ]
