# Generated by Django 5.2.7 on 2025-10-24 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0031_uploadinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='alumno_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='conciliado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='conciliado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='conciliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_banco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientobanco',
            name='pago_creado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_banco', to='alumnos.pagodiario'),
        ),
    ]
