# Generated by Django 5.2.7 on 2025-10-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0032_movimientobanco_alumno_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobanco',
            name='nombre_detectado_save',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
