# Generated by Django 5.2.7 on 2025-10-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0033_movimientobanco_nombre_detectado_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobanco',
            name='pago_creado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_banco', to='alumnos.pagodiario'),
        ),
    ]
