# Generated by Django 5.2.7 on 2025-10-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0034_alter_movimientobanco_pago_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodiario',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to='alumnos.movimientobanco'),
        ),
    ]
