# Generated by Django 5.2.7 on 2025-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0035_pagodiario_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodiario',
            name='pago_oportuno',
            field=models.BooleanField(default=True),
        ),
    ]
