# Generated by Django 5.2.7 on 2025-10-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0036_pagodiario_pago_oportuno'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamiento',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiamientos', to='alumnos.programa', verbose_name='Programa'),
        ),
    ]
