# Generated by Django 5.2.7 on 2025-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0037_financiamiento_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodiario',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
