# Generated by Django 5.2.7 on 2025-10-31 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0038_alter_pagodiario_forma_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionescolar',
            name='bienvenida_enviada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Bienvenida enviada'),
        ),
        migrations.AddField(
            model_name='informacionescolar',
            name='bienvenida_enviada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bienvenida enviada en'),
        ),
        migrations.AddField(
            model_name='informacionescolar',
            name='bienvenida_enviada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienvenidas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Bienvenida enviada por'),
        ),
    ]
