# Generated by Django 5.2.7 on 2025-10-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0039_informacionescolar_bienvenida_enviada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentotipo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AddField(
            model_name='documentotipo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas u observaciones adicionales para el alumno o control interno.'),
        ),
        migrations.AddField(
            model_name='documentotipo',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Orden de aparición en listados y formularios.'),
        ),
        migrations.AddField(
            model_name='documentotipo',
            name='presentacion',
            field=models.CharField(blank=True, help_text='Ej.: Original / Original y copia / 2 copias / 1 copia.', max_length=120, verbose_name='Presentación'),
        ),
        migrations.AddIndex(
            model_name='documentotipo',
            index=models.Index(fields=['orden'], name='alumnos_doc_orden_c72f64_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotipo',
            index=models.Index(fields=['activo'], name='alumnos_doc_activo_5a3e38_idx'),
        ),
    ]
