# Generated by Django 5.2.7 on 2025-11-01 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0040_alter_documentotipo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaReinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text="Etiqueta opcional, p.ej. 'A los 9 meses'", max_length=120)),
                ('meses_offset', models.PositiveIntegerField(help_text='Mes en el que se cobra, contado desde el inicio (1 = al 1er mes, 9 = al 9º mes, etc.).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mes de cobro')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de reinscripción',
                'verbose_name_plural': 'Reglas de reinscripción',
                'ordering': ['meses_offset', 'nombre'],
                'indexes': [models.Index(fields=['meses_offset'], name='alumnos_reg_meses_o_cd0e05_idx'), models.Index(fields=['activo'], name='alumnos_reg_activo_4a4ec3_idx')],
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='regla_reinscripcion',
            field=models.ForeignKey(blank=True, help_text='Define en qué mes se cobra la reinscripción (usa el monto de este Programa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='alumnos.reglareinscripcion', verbose_name='Regla de reinscripción'),
        ),
    ]
