# Generated by Django 5.2.7 on 2025-11-01 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0041_reglareinscripcion_programa_regla_reinscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='regla_reinscripcion',
        ),
        migrations.CreateModel(
            name='ReinscripcionHito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text="Etiqueta opcional (p.ej. 'Mes 9').", max_length=120)),
                ('meses_offset', models.PositiveIntegerField(help_text='Mes contado desde el inicio (1=primer mes, 9=noveno mes, etc.)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mes de cobro')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Si lo dejas vacío, usa Programa.reinscripcion.', max_digits=12, null=True, verbose_name='Monto (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscripciones_hitos', to='alumnos.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Hito de reinscripción',
                'verbose_name_plural': 'Hitos de reinscripción',
                'ordering': ['meses_offset', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ReglaReinscripcion',
        ),
        migrations.AddIndex(
            model_name='reinscripcionhito',
            index=models.Index(fields=['programa', 'meses_offset'], name='alumnos_rei_program_43a7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='reinscripcionhito',
            index=models.Index(fields=['activo'], name='alumnos_rei_activo_32ed19_idx'),
        ),
        migrations.AddConstraint(
            model_name='reinscripcionhito',
            constraint=models.UniqueConstraint(fields=('programa', 'meses_offset'), name='uniq_hito_programa_mes'),
        ),
    ]
