# Generated by Django 5.2.7 on 2025-11-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0042_remove_programa_regla_reinscripcion_and_more'),
        ('cobros', '0002_alter_paymentrecord_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodiario',
            name='payment_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_diario', to='cobros.paymentrecord'),
        ),
    ]
