# Generated by Django 5.2.7 on 2025-11-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0043_pagodiario_payment_record'),
        ('cobros', '0003_paymentrecord_cargo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagodiario',
            index=models.Index(fields=['creado_en'], name='alumnos_pag_creado__e21c29_idx'),
        ),
    ]
