# Generated by Django 5.2.7 on 2025-11-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0044_pagodiario_alumnos_pag_creado__e21c29_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionescolar',
            name='grupo',
            field=models.CharField(blank=True, help_text="LEGACY / DEPRECADO: Se usará sólo si no hay 'Grupo (nuevo)'.", max_length=50, null=True, verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador corto (sin espacios). Ej.: a-2025-1', max_length=60, verbose_name='Código de grupo')),
                ('nombre', models.CharField(help_text='Etiqueta que verá el usuario. Ej.: A 2025-1 Vespertino', max_length=120, verbose_name='Nombre visible')),
                ('activo', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='alumnos.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['programa__codigo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='informacionescolar',
            name='grupo_nuevo',
            field=models.ForeignKey(blank=True, help_text="Selecciona un grupo del catálogo. Si está vacío se usará el campo 'Grupo' (LEGACY).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='alumnos.grupo', verbose_name='Grupo (nuevo)'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['programa', 'codigo'], name='alumnos_gru_program_ddd76b_idx'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['activo'], name='alumnos_gru_activo_6a2dfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('programa', 'codigo')},
        ),
    ]
