# Generated by Django 5.2.7 on 2025-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0045_alter_informacionescolar_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='rvoe_clave',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='R.V.O.E.'),
        ),
        migrations.AddField(
            model_name='programa',
            name='rvoe_emisor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Emisor R.V.O.E. (SEP/Estado)'),
        ),
        migrations.AddField(
            model_name='programa',
            name='rvoe_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha R.V.O.E.'),
        ),
        migrations.AddField(
            model_name='programa',
            name='rvoe_url',
            field=models.URLField(blank=True, verbose_name='URL del acuerdo (opcional)'),
        ),
    ]
