# Generated by Django 5.2.7 on 2025-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0046_programa_rvoe_clave_programa_rvoe_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password_email_institucional',
            field=models.CharField(blank=True, help_text='Se almacena en texto plano. PROTEGER este dato.', max_length=128, verbose_name='Contraseña correo institucional (texto plano)'),
        ),
    ]
