# Generated by Django 5.2.7 on 2025-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0047_alumno_password_email_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionescolar',
            name='grupo_oficial',
            field=models.CharField(blank=True, help_text='Grupo oficial asignado al alumno.', max_length=50, null=True, verbose_name='Grupo oficial'),
        ),
    ]
