# Generated by Django 5.2.7 on 2025-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_intentoquiz_pregunta_opcionpregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='lms/cursos_portadas/', verbose_name='Imagen del curso'),
        ),
    ]
