# Generated by Django 5.2.7 on 2025-11-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_curso_fecha_fin_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='embed_video',
            field=models.TextField(blank=True),
        ),
    ]
