"""
Django settings for campusiuaf project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jd4waq35fus*+^n_^a+nn*5dcg2kj%^@f1k3ee_=j_$-7-toq^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'alumnos',
]

SITE_ID = 1  # importante para allauth
AUTHENTICATION_BACKENDS = [
    # Permite login con admin clásico
    "django.contrib.auth.backends.ModelBackend",
    # Backend de allauth
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Dónde mandar después del login/logout
LOGIN_REDIRECT_URL = "principal"   # o la ruta que quieras
LOGOUT_REDIRECT_URL = "account_login"

# Configuración típica de cuentas
# Permitir login con usuario y/o email
ACCOUNT_LOGIN_METHODS = {"username", "email"}   # {'username'}, {'email'} o ambas

# Campos del formulario de registro (los * son obligatorios)
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Rate limits (ejemplo equivalente a tus límites antiguos)
ACCOUNT_RATE_LIMITS = {
    # Máx. 5 fallos por 5 minutos (300s). Ajusta a tu gusto.
    "login_failed": "5/300s",
    # Puedes afinar más cosas:
    # "login_success": "20/m",
    # "signup": "5/h",
    # "password_reset": "5/h",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
      "allauth.account.middleware.AccountMiddleware",   # <-- REQUERIDO por allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campusiuaf.urls'

# Después (allauth):
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "principal"
LOGOUT_REDIRECT_URL = "account_login"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],  # asegúrate de tenerlo
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",   # <- NECESARIO para allauth
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'campusiuaf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
#TIME_ZONE = 'UTC'
#USE_I18N = True
#USE_TZ = True

LANGUAGE_CODE = "es-mx"
TIME_ZONE = "America/Cancun"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_DIRS = [
    BASE_DIR / "static",   # <-- carpeta global de estáticos del proyecto
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ACCOUNT_AUTHENTICATION_METHOD = "username_email"   # o "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"  # "mandatory" si quieres exigir verificación
DEFAULT_FROM_EMAIL = "no-reply@tu-dominio.com"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # dev
# En prod: django.core.mail.backends.smtp.EmailBackend + credenciales SMTP
