"""
Django settings for campusiuaf project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent
# Cargar .env (antes de leer variables)
load_dotenv(BASE_DIR / ".env")




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", default='django-insecure-jd4waq35fus*+^n_^a+nn*5dcg2kj%^@f1k3ee_=j_$-7-toq^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", default=True) in [True, 'True', '1', 1]

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", default="localhost").split(",")

CSRF_TRUSTED_ORIGINS = ["https://admin.campusiuaf.com"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',   
    "django.contrib.humanize",
    'alumnos',
    'cobros',
    "academico",
    "lms",    
    "oauth2_provider",
    
]





SITE_ID = 1  # importante para allauth
AUTHENTICATION_BACKENDS = [
    # Permite login con admin clásico
    "django.contrib.auth.backends.ModelBackend",
    # Backend de allauth
    "allauth.account.auth_backends.AuthenticationBackend",
]


OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    # Debe ser la URL pública del issuer, sin barra final
    "OIDC_ISS_ENDPOINT": "https://admin.campusiuaf.com",

    # Define scopes, OIDC necesita 'openid' (y opcionalmente 'profile'/'email')
    "SCOPES": {
        "read": "Read access",
        "write": "Write access",
        "openid": "OpenID Connect scope",
        "profile": "User profile",
        "email": "User email",
    },
}



# Dónde mandar después del login/logout
LOGIN_REDIRECT_URL = "alumnos:principal"   # o la ruta que quieras
LOGOUT_REDIRECT_URL = "account_login"

# Configuración típica de cuentas
# Permitir login con usuario y/o email
ACCOUNT_LOGIN_METHODS = {"username", "email"}   # {'username'}, {'email'} o ambas

# Campos del formulario de registro (los * son obligatorios)
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Rate limits (ejemplo equivalente a tus límites antiguos)
ACCOUNT_RATE_LIMITS = {
    # Máx. 5 fallos por 5 minutos (300s). Ajusta a tu gusto.
    "login_failed": "5/300s",
    # Puedes afinar más cosas:
    # "login_success": "20/m",
    # "signup": "5/h",
    # "password_reset": "5/h",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
      "allauth.account.middleware.AccountMiddleware",   # <-- REQUERIDO por allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campusiuaf.urls'

# Después (allauth):
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "alumnos:principal"
LOGOUT_REDIRECT_URL = "account_login"


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],  # asegúrate de tenerlo
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",   # <- NECESARIO para allauth
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'campusiuaf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---- Bases de datos
if DEBUG:
    # Desarrollo: SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Producción: Postgres (Docker compose: servicio 'db')
    # Opción A: variables sueltas del .env
    POSTGRES_DB = os.environ.get("POSTGRES_DB", "miapp_db")
    POSTGRES_USER = os.environ.get("POSTGRES_USER", "miapp_user")
    POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "miapp_password")
    POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "db")  # nombre del servicio en compose
    POSTGRES_PORT = int(os.environ.get("POSTGRES_PORT", "5432"))

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
            "CONN_MAX_AGE": 600,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
#TIME_ZONE = 'UTC'
#USE_I18N = True
#USE_TZ = True

LANGUAGE_CODE = "es-mx"
TIME_ZONE = "America/Cancun"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC
STATIC_URL = "/static/"

# Fuentes (tu carpeta con assets del proyecto)
STATICFILES_DIRS = [ BASE_DIR / "static" ]  # /app/static (fuente)

# Destino de collectstatic (separado de la fuente)
STATIC_ROOT = BASE_DIR / "staticfiles"      # /app/staticfiles (salida)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

###################################################################################
# Config común SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

#if DEBUG:
#    EMAIL_HOST_USER = "yatniel@gmail.com"
#    EMAIL_HOST_PASSWORD = "nswl rsga zyna cpte"  # app password de 16 caracteres (con espacios, ok)
#    DEFAULT_FROM_EMAIL = "CampusIUAF <yatniel@gmail.com>"
#else:
# Cuenta por defecto (recibos) para cosas genéricas
EMAIL_HOST_USER = "recibos@iuaf.edu.mx"
EMAIL_HOST_PASSWORD = "estl jtbs jeyx lkkx"  # app password de 16 caracteres (con espacios, ok)
DEFAULT_FROM_EMAIL = "CampusIUAF Recibos <recibos@iuaf.edu.mx>"

    ##################################################################################
# === CREDENCIALES EXTRA PARA USAR cadministrativo EMAIL EN ADMISIONES
ADM_EMAIL_USER = "cadministrativa@iuaf.edu.mx"
ADM_EMAIL_PASSWORD = "xywy uuch vkyu hbzi"   # app password de Gmail
WELCOME_FROM_EMAIL = "CampusIUAF Admisiones <cadministrativa@iuaf.edu.mx>"
    
            



##################################################################################
# ======================
# STRIPE (config directa temporal)
# ======================


STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY      = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET  = os.getenv("STRIPE_WEBHOOK_SECRET", "")




# URLs a donde Stripe redirige después del checkout
FRONTEND_SUCCESS_URL = "https://admin.campusiuaf.com/cobros/exito/"
FRONTEND_CANCEL_URL  = "https://admin.campusiuaf.com/cobros/cancelado/"

# (Opcional) Estructura agrupada, por si te gusta acceder como dict:
STRIPE_CONFIG = {
    "PUBLISHABLE_KEY": STRIPE_PUBLISHABLE_KEY,
    "SECRET_KEY": STRIPE_SECRET_KEY,
    "WEBHOOK_SECRET": STRIPE_WEBHOOK_SECRET,
    "SUCCESS_URL": FRONTEND_SUCCESS_URL,
    "CANCEL_URL": FRONTEND_CANCEL_URL,
}



# Seguridad básica en prod (si ya estás detrás de HTTPS real)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


MASIVO_HEADER_URL = "https://admin.campusiuaf.com/static/iuaf/doctorado-header3.png"
MASIVO_DOCTORADO_CTA_URL = "https://https://admin.campusiuaf.com/doctorados"
